---
driver:
  name: docker
  privileged: true
  volume: /sys/fs/cgroup:/sys/fs/cgroup
  provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config

provisioner:
  name: ansible_playbook
  hosts: localhost
  requirements_path: requirements.yml
  playbook: tests/test.yml
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_omnibus: false
  idempotency_test: true

verifier:
  name: inspec
  inspec_tests:
    - path: tests/inspec

platforms:
  - name: archlinux-rolling
    driver:
      image: diodonfrost/archlinux-rolling-ansible
      platform: arch
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd

suites:
  - name: default
