---
- name: Docker | Install package
  package:
    name: docker
    state: present

- name: Docker | Managed group
  group:
    name: docker
    state: present

- name: Docker | Allow current user to use Docker
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Docker | Managed service
  service:
    name: docker
    enabled: yes
    state: started

- name: Podman | Install packages
  package:
    name:
      - podman
      - crun
    state: present

- name: Podman | Set subuid
  copy:
    content: "{{ ansible_user_id }}:165536:4096"
    dest: /etc/subuid
    owner: root
    group: root
    mode: '0644'

- name: Podman | Set subgid
  copy:
    content: "{{ ansible_user_id }}:165536:4096"
    dest: /etc/subgid
    owner: root
    group: root
    mode: '0644'
