name: molecule

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: molecule test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Molecule
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint molecule-docker docker

      - name: Test Ansible playbook
        run: |
          molecule test
